version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: shakeb
      MYSQL_USER: shakeb
      MYSQL_PASSWORD: shakeb3
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql